[project]
name = "multi-robot-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mjlab>=1.1.0",
]

[project.scripts]
multi-robot-rl = "multi_robot_rl:main"
train = "multi_robot_rl.cli_shims:train_main"
play = "multi_robot_rl.cli_shims:play_main"

[project.entry-points."mjlab.tasks"]
multi_robot_rl = "multi_robot_rl"

[build-system]
requires = ["uv_build>=0.10.11,<0.11.0"]
build-backend = "uv_build"

[tool.uv.sources]
mjlab = { git = "https://github.com/mujocolab/mjlab.git" }

[dependency-groups]
dev = [
    "mkdocs-gen-files>=0.6.1",
    "mkdocs-literate-nav>=0.6.3",
    "mkdocs-material>=9.7.6",
    "mkdocs-mermaid2-plugin>=1.2.3",
    "mkdocstrings[python]>=1.0.3",
]
