"""Bridges the gap between the masspoint's EntityCfg and the RobotConfig used for task definitions."""
import mujoco
import torch
from pathlib import Path

from mjlab.managers.scene_entity_config import SceneEntityCfg
from mjlab.managers.observation_manager import ObservationTermCfg
from mjlab.managers.event_manager import EventTermCfg
from mjlab.entity import EntityCfg, EntityArticulationInfoCfg
from mjlab.actuator import XmlActuatorCfg
from mjlab.envs.mdp import actions
from mjlab.envs import ManagerBasedRlEnv
from mjlab.utils.lab_api.math import sample_uniform

from multi_robot_rl.assets.robots.base import RobotConfig
from multi_robot_rl.common import mdp as mdp_common
from multi_robot_rl.configs import type_constants, reach_constants, push_constants


_MP_JOINT_NAMES = ("mp_x", "mp_y", "mp_z")

# =========================================================
# Articulation (Actuator Configuration)
# Note: Configuration is in configs/<task>_constants.py
# and autogenerated in the XML files
# =========================================================

def _masspoint_articulation() -> EntityArticulationInfoCfg:
    return EntityArticulationInfoCfg(
        actuators=(XmlActuatorCfg(target_names_expr=_MP_JOINT_NAMES),),
    )

# =========================================================
# EntityCfg getters 
# =========================================================

def _get_masspoint_entity_cfg(xml_filename: str, init_z: float) -> EntityCfg:
    """Generic Helper for getting masspoint EntityCfgs for different tasks, which differ only in the XML used and the initial z position."""
    def get_spec() -> mujoco.MjSpec:
        import multi_robot_rl.assets.scripts.generate_xmls as generate_xmls
        _ASSETS_DIR = Path(__file__).parent.parent
        _GENERATED_XML_DIR = _ASSETS_DIR / "generated"
        generate_xmls.generate_all()
        return mujoco.MjSpec.from_file(str(_GENERATED_XML_DIR / xml_filename))
    return EntityCfg(
        spec_fn=get_spec,
        articulation=_masspoint_articulation(),
        init_state=EntityCfg.InitialStateCfg(
            joint_pos={name: 0.0 for name in _MP_JOINT_NAMES},
            joint_vel={".*": 0.0},
        ),
    )

def get_masspoint_entity_cfg_for_type_task() -> EntityCfg:
    return _get_masspoint_entity_cfg("masspoint_type_task.xml", type_constants.MP_Z_RANGE[1])

def get_masspoint_entity_cfg_for_reach_task() -> EntityCfg:
    return _get_masspoint_entity_cfg("masspoint_reach_task.xml", reach_constants.MP_Z_RANGE[1])

def get_masspoint_entity_cfg_for_push_task() -> EntityCfg:
    return _get_masspoint_entity_cfg("masspoint_push_task.xml", push_constants.MP_Z_RANGE[1])

# =========================================================
# RobotConfig getters 
# =========================================================

def _get_masspoint_robot_config(
    name: str,
    entity_cfg: EntityCfg,
    vel_ranges: tuple[tuple, tuple, tuple],
    pos_ranges: tuple[tuple[float, float], tuple[float, float], tuple[float, float]] | None = None,
    cylinder_radius: float | None = None,
    cylinder_height: float | None = None,
    cylinder_height_fixed: bool | None = None,
) -> RobotConfig:
    """
    Generic helper for getting masspoint RobotConfigs for different tasks, which differ only in the entity_cfg and randomization ranges.

    Exactly one of pos_ranges or (cylinder_radius + cylinder_height + cylinder_height_fixed) must be provided.

    Args:
        name: Name of the robot.
        entity_cfg: EntityCfg for the masspoint.
        vel_ranges: ((x_min, x_max), (y_min, y_max), (z_min, z_max)).
        pos_ranges: ((x_min, x_max), (y_min, y_max), (z_min, z_max)).
        cylinder_radius: Radius of the cylinder for uniform cylinder reset.
        cylinder_height: Height of the cylinder for uniform cylinder reset.
        cylinder_height_fixed: bool indicating whether to set height to fixed cylinder_height (true) or sample uniformly in [0, cylinder_height] (false).

    Returns:
        RobotConfig: The RobotConfig for the masspoint.
    """
    use_cylinder = cylinder_radius is not None and cylinder_height is not None and cylinder_height_fixed is not None
    use_pos_ranges = pos_ranges is not None
    if use_cylinder == use_pos_ranges:
        raise ValueError("Provide either pos_ranges or both cylinder_radius and cylinder_height, not both or neither.")

    asset_cfg = SceneEntityCfg(name, joint_names=_MP_JOINT_NAMES)
    x_vel_range, y_vel_range, z_vel_range = vel_ranges

    if use_cylinder:
        reset_func = _reset_masspoint_joints_cylinder
        reset_params = {
            "cylinder_radius": cylinder_radius,
            "cylinder_height": cylinder_height,
            "cylinder_height_fixed": cylinder_height_fixed,
            "x_velocity_range": x_vel_range,
            "y_velocity_range": y_vel_range,
            "z_velocity_range": z_vel_range,
            "asset_cfg": asset_cfg,
        }
    else:
        x_pos_range, y_pos_range, z_pos_range = pos_ranges
        reset_func = _reset_masspoint_joints
        reset_params = {
            "x_pos_range": x_pos_range,
            "y_pos_range": y_pos_range,
            "z_pos_range": z_pos_range,
            "x_velocity_range": x_vel_range,
            "y_velocity_range": y_vel_range,
            "z_velocity_range": z_vel_range,
            "asset_cfg": asset_cfg,
        }

    return RobotConfig(
        entity_cfg=entity_cfg,
        name=name,
        joint_names=_MP_JOINT_NAMES,
        end_effector_site="masspoint_center",
        action_terms={
            f"{name}_velocity": actions.JointVelocityActionCfg(
                entity_name=name,
                actuator_names=_MP_JOINT_NAMES,
                scale=1.0,
            )
        },
        obs_terms={
            f"{name}_joint_pos": ObservationTermCfg(func=mdp_common.joint_pos_abs, params={"asset_cfg": asset_cfg}),
            f"{name}_joint_vel": ObservationTermCfg(func=mdp_common.joint_vel_abs, params={"asset_cfg": asset_cfg}),
        },
        reset_terms={
            f"{name}_reset": EventTermCfg(
                func=reset_func,
                mode="reset",
                params=reset_params,
            )
        },
    )


def get_masspoint_robot_config_type_task(name: str) -> RobotConfig:
    return _get_masspoint_robot_config(
        name,
        entity_cfg=get_masspoint_entity_cfg_for_type_task(),
        pos_ranges=(type_constants.MP_X_POS_RANDOM_RANGE, type_constants.MP_Y_POS_RANDOM_RANGE, type_constants.MP_Z_POS_RANDOM_RANGE),
        vel_ranges=(type_constants.MP_X_VEL_RANDOM_RANGE, type_constants.MP_Y_VEL_RANDOM_RANGE, type_constants.MP_Z_VEL_RANDOM_RANGE),
    )


def get_masspoint_robot_config_reach_task(name: str) -> RobotConfig:
    return _get_masspoint_robot_config(
        name,
        entity_cfg=get_masspoint_entity_cfg_for_reach_task(),
        vel_ranges=(reach_constants.MP_X_VEL_RANDOM_RANGE, reach_constants.MP_Y_VEL_RANDOM_RANGE, reach_constants.MP_Z_VEL_RANDOM_RANGE),
        cylinder_radius=reach_constants.MP_SPAWN_RADIUS,
        cylinder_height=reach_constants.MP_SPAWN_HEIGHT,
        cylinder_height_fixed=False,
    )


def get_masspoint_robot_config_push_task(name: str) -> RobotConfig:
    return _get_masspoint_robot_config(
        name,
        entity_cfg=get_masspoint_entity_cfg_for_push_task(),
        vel_ranges=(push_constants.MP_X_VEL_RANDOM_RANGE, push_constants.MP_Y_VEL_RANDOM_RANGE, push_constants.MP_Z_VEL_RANDOM_RANGE),
        cylinder_radius=push_constants.MP_SPAWN_RADIUS,
        cylinder_height=push_constants.MP_SPAWN_HEIGHT,
        cylinder_height_fixed=True,
    )

# =========================================================
# Reset function
# =========================================================

def _reset_masspoint_joints(
    env: ManagerBasedRlEnv,
    env_ids: torch.Tensor | None,
    x_pos_range: tuple[float, float],
    y_pos_range: tuple[float, float],
    z_pos_range: tuple[float, float],
    x_velocity_range: tuple[float, float],
    y_velocity_range: tuple[float, float],
    z_velocity_range: tuple[float, float],
    asset_cfg: SceneEntityCfg,
) -> None:
    """
    Reset masspoint position and velocity with randomly sampled deviations from the default state.

    Args:
        env: The environment containing the masspoint asset.
        env_ids: is handled by mjlab
        x_pos_range: Range for random deviation in x position.
        y_pos_range: Range for random deviation in y position.
        z_pos_range: Range for random deviation in z position.
        x_velocity_range: Range for random deviation in x velocity.
        y_velocity_range: Range for random deviation in y velocity.
        z_velocity_range: Range for random deviation in z velocity.
        asset_cfg: The SceneEntityCfg for the masspoint asset, containing joint information.
    """
    if env_ids is None:
        env_ids = torch.arange(env.num_envs, device=env.device, dtype=torch.int)

    asset = env.scene[asset_cfg.name]
    default_joint_pos = asset.data.default_joint_pos
    default_joint_vel = asset.data.default_joint_vel

    # Positional state (x, y, z)
    joint_pos = default_joint_pos[env_ids][:, asset_cfg.joint_ids].clone()
    joint_pos[:, 0] += sample_uniform(*x_pos_range, (len(env_ids),), env.device)
    joint_pos[:, 1] += sample_uniform(*y_pos_range, (len(env_ids),), env.device)
    joint_pos[:, 2] += sample_uniform(*z_pos_range, (len(env_ids),), env.device)

    # Velocity state (x, y, z)
    joint_vel = default_joint_vel[env_ids][:, asset_cfg.joint_ids].clone()
    joint_vel[:, 0] += sample_uniform(*x_velocity_range, (len(env_ids),), env.device)
    joint_vel[:, 1] += sample_uniform(*y_velocity_range, (len(env_ids),), env.device)
    joint_vel[:, 2] += sample_uniform(*z_velocity_range, (len(env_ids),), env.device)

    # Format IDs mapping
    joint_ids = asset_cfg.joint_ids
    if isinstance(joint_ids, list):
        joint_ids = torch.tensor(joint_ids, device=env.device)

    asset.write_joint_state_to_sim(
        joint_pos,
        joint_vel,
        env_ids=env_ids,
        joint_ids=joint_ids,
    )


def _reset_masspoint_joints_cylinder(
    env: ManagerBasedRlEnv,
    env_ids: torch.Tensor | None,
    cylinder_radius: float,
    cylinder_height: float,
    cylinder_height_fixed: bool,
    x_velocity_range: tuple[float, float],
    y_velocity_range: tuple[float, float],
    z_velocity_range: tuple[float, float],
    asset_cfg: SceneEntityCfg,
) -> None:
    """
    Reset masspoint position uniformly distributed in a cylinder around default_joint_pos.

    XY sampling uses the area-preserving sqrt trick for uniform disk coverage.
    Z is sampled uniformly in [0, cylinder_height] if cylinder_height_fixed is False, otherwise it's set to cylinder_height.

    Args:
        env: The environment containing the masspoint asset.
        env_ids: is handled by mjlab
        cylinder_radius: Radius of the cylinder.
        cylinder_height: Height of the cylinder.
        cylinder_height_fixed: Indicates whether to set height to fixed cylinder_height or sample uniformly in [0, cylinder_height].
        x_velocity_range: Range for random deviation in x velocity.
        y_velocity_range: Range for random deviation in y velocity.
        z_velocity_range: Range for random deviation in z velocity.
        asset_cfg: The SceneEntityCfg for the masspoint asset, containing joint information.
    """
    if env_ids is None:
        env_ids = torch.arange(env.num_envs, device=env.device, dtype=torch.int)

    asset = env.scene[asset_cfg.name]
    default_joint_pos = asset.data.default_joint_pos
    default_joint_vel = asset.data.default_joint_vel
    n = len(env_ids)

    # Uniform distribution in a disk: r = R * sqrt(U), theta = 2*pi*U
    r = cylinder_radius * torch.sqrt(torch.rand(n, device=env.device))
    theta = 2.0 * torch.pi * torch.rand(n, device=env.device)

    joint_pos = default_joint_pos[env_ids][:, asset_cfg.joint_ids].clone()
    joint_pos[:, 0] += r * torch.cos(theta)
    joint_pos[:, 1] += r * torch.sin(theta)
    # joint_pos[:, 2] += cylinder_height * torch.rand(n, device=env.device)
    if cylinder_height_fixed:
        joint_pos[:, 2] += cylinder_height
    else:
        joint_pos[:, 2] += cylinder_height * torch.rand(n, device=env.device)

    joint_vel = default_joint_vel[env_ids][:, asset_cfg.joint_ids].clone()
    joint_vel[:, 0] += sample_uniform(*x_velocity_range, (n,), env.device)
    joint_vel[:, 1] += sample_uniform(*y_velocity_range, (n,), env.device)
    joint_vel[:, 2] += sample_uniform(*z_velocity_range, (n,), env.device)

    joint_ids = asset_cfg.joint_ids
    if isinstance(joint_ids, list):
        joint_ids = torch.tensor(joint_ids, device=env.device)

    asset.write_joint_state_to_sim(
        joint_pos,
        joint_vel,
        env_ids=env_ids,
        joint_ids=joint_ids,
    )
