"""Bridges the gap between the UR10e's EntityCfg and the RobotConfig used for task definitions."""
import mujoco
import torch
from pathlib import Path
from math import pi, sin, cos

from mjlab.managers.scene_entity_config import SceneEntityCfg
from mjlab.managers.observation_manager import ObservationTermCfg
from mjlab.managers.event_manager import EventTermCfg
from mjlab.entity import EntityCfg, EntityArticulationInfoCfg
from mjlab.actuator import BuiltinPositionActuatorCfg
from mjlab.envs.mdp import actions
from mjlab.envs import ManagerBasedRlEnv
from mjlab.utils.lab_api.math import sample_uniform

from multi_robot_rl.assets.robots.base import RobotConfig
from multi_robot_rl.common import mdp as mdp_common


UR10_HOME_JOINT_POS = (-pi/2, -pi/2, pi/2, -pi/2, -pi/2, 0.0)
UR10_JOINT_NAMES = (
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
)

def get_ur10_base_poses(
    n: int,
    radius: float = 0.65,
) -> list[tuple[tuple[float, float, float], tuple[float, float, float, float]]]:
    """
    Returns (pos, rot) for n UR10s evenly distributed on a circle of given radius,
    each rotated to face the origin (inward).

    Angle θ is measured CCW from the +y axis, so:
      θ=0        → pos (0, +R, 0), facing -y  [matches the original single-robot placement]
      θ=π/2      → pos (+R, 0, 0), facing -x
      θ=π        → pos (0, -R, 0), facing +y
      θ=3π/2     → pos (-R, 0, 0), facing +x

    The rotation quaternion [w, x, y, z] = (cos((π-θ)/2), 0, 0, sin((π-θ)/2))
    rotates the UR10 model (whose local working direction is +y) to face inward.
    """
    poses = []
    for k in range(n):
        theta = 2 * pi * k / n
        pos = (round(radius * sin(theta), 8), round(radius * cos(theta), 8), 0.0)

        # Rotation around z by (π − θ) orients the arm's +y local axis toward -inward direction
        alpha = pi - theta
        rot = (round(cos(alpha / 2), 8), 0.0, 0.0, round(sin(alpha / 2), 8))
        poses.append((pos, rot))
    return poses

# =========================================================
# Articulation (Actuator Configuration)
# Note: Configuration is in configs/<task>_constants.py
# and autogenerated in the XML files
# =========================================================

def _ur10_articulation() -> EntityArticulationInfoCfg:
    return EntityArticulationInfoCfg(
        actuators=(
            BuiltinPositionActuatorCfg(
                target_names_expr=("shoulder_pan_joint", "shoulder_lift_joint"),
                stiffness=5000.0,
                damping=500.0,
                effort_limit=330.0,
            ),
            BuiltinPositionActuatorCfg(
                target_names_expr=("elbow_joint",),
                stiffness=5000.0,
                damping=500.0,
                effort_limit=150.0,
            ),
            BuiltinPositionActuatorCfg(
                target_names_expr=("wrist_1_joint", "wrist_2_joint", "wrist_3_joint"),
                stiffness=5000.0,
                damping=250.0,
                effort_limit=56.0,
            ),
        ),
    )

# =========================================================
# Initial State getter
# =========================================================

def _ur10_init_state(pos, rot) -> EntityCfg.InitialStateCfg:
    home = UR10_HOME_JOINT_POS
    return EntityCfg.InitialStateCfg(
        pos=pos,
        rot=rot,
        joint_pos={name: p for name, p in zip(UR10_JOINT_NAMES, home)},
        joint_vel={".*": 0.0},
    )

# =========================================================
# EntityCfg getters 
# =========================================================

def _get_ur10e_entity_cfg(
    pos: tuple[float, float, float],
    rot: tuple[float, float, float, float],
    joint_pos_limits: dict | None = None,
) -> EntityCfg:
    """
    Generic helper for getting UR10e EntityCfgs for different tasks, which differ only in the joint position limits.

    Args:
        pos: Initial position of the UR10 base.
        rot: Initial rotation (quaternion) of the UR10 base.
        joint_pos_limits: Optional dict mapping joint names to (min, max) position limits.
    """
    def get_spec() -> mujoco.MjSpec:
        import multi_robot_rl.assets.scripts.generate_xmls as generate_xmls
        generate_xmls.generate_all()
        _ASSETS_DIR = Path(__file__).parent.parent
        spec = mujoco.MjSpec.from_file(str(_ASSETS_DIR / "robots/ur10e.xml"))
        if joint_pos_limits:
            for joint in spec.joints:
                if joint.name in joint_pos_limits:
                    lo, hi = joint_pos_limits[joint.name]
                    joint.range = [lo, hi]
        return spec
    return EntityCfg(
        spec_fn=get_spec,
        articulation=_ur10_articulation(),
        init_state=_ur10_init_state(pos, rot),
    )


def _assert_ur10_joint_limits_include_home_pose(joint_pos_limits: dict) -> None:
    """
    Assert that the provided joint position limits include the UR10 home pose, to avoid accidentally creating impossible tasks.
    """
    for i, joint_name in enumerate(UR10_JOINT_NAMES):
        home_pos = UR10_HOME_JOINT_POS[i]
        if joint_name in joint_pos_limits:
            lo, hi = joint_pos_limits[joint_name]
            assert lo <= home_pos <= hi, f"Joint '{joint_name}' home position {home_pos} is outside the provided limits ({lo}, {hi})."

def get_ur10e_entity_cfg_for_type_task(pos, rot) -> EntityCfg:
    from multi_robot_rl.configs import type_constants
    _assert_ur10_joint_limits_include_home_pose(type_constants.UR10_JOINT_POS_LIMITS)
    return _get_ur10e_entity_cfg(pos, rot, joint_pos_limits=type_constants.UR10_JOINT_POS_LIMITS)

def get_ur10e_entity_cfg_for_reach_task(pos, rot) -> EntityCfg:
    from multi_robot_rl.configs import reach_constants
    _assert_ur10_joint_limits_include_home_pose(reach_constants.UR10_JOINT_POS_LIMITS)
    return _get_ur10e_entity_cfg(pos, rot, joint_pos_limits=reach_constants.UR10_JOINT_POS_LIMITS)

def get_ur10e_entity_cfg_for_push_task(pos, rot) -> EntityCfg:
    from multi_robot_rl.configs import push_constants
    _assert_ur10_joint_limits_include_home_pose(push_constants.UR10_JOINT_POS_LIMITS)
    return _get_ur10e_entity_cfg(pos, rot, joint_pos_limits=push_constants.UR10_JOINT_POS_LIMITS)

# =========================================================
# RobotConfig getters 
# =========================================================

def _get_ur10_robot_config(
    name: str,
    entity_cfg: EntityCfg,
    joint_reset_range: tuple[float, float],
) -> RobotConfig:
    """
    Generic helper for getting UR10e RobotConfigs for different tasks, which differ only in the entity_cfg and joint reset range.
    
    Args:
        name: Name of the robot.
        entity_cfg: EntityCfg for the UR10e.
        joint_reset_range: Tuple specifying the uniform range for randomizing the joint reset position around the home pose (applied independently to each joint).

    Returns:
        RobotConfig: The RobotConfig for the UR10e.
    """
    asset_cfg = SceneEntityCfg(name, joint_names=UR10_JOINT_NAMES)
    return RobotConfig(
        entity_cfg=entity_cfg,
        name=name,
        joint_names=UR10_JOINT_NAMES,
        end_effector_site="attachment_site",
        action_terms={
            f"{name}_position": actions.RelativeJointPositionActionCfg(
                entity_name=name,
                actuator_names=UR10_JOINT_NAMES,
                scale=0.3,
            )
        },
        obs_terms={
            f"{name}_ee_pos": ObservationTermCfg(func=mdp_common.ee_pos_obs, params={"robot_name": name, "ee_site": "attachment_site"}),
            f"{name}_joint_pos": ObservationTermCfg(func=mdp_common.joint_pos_abs, params={"asset_cfg": asset_cfg}),
            f"{name}_joint_vel": ObservationTermCfg(func=mdp_common.joint_vel_abs, params={"asset_cfg": asset_cfg}),
        },
        reset_terms={
            f"{name}_reset": EventTermCfg(
                func=_reset_ur10_joints,
                mode="reset",
                params={
                    "joint_reset_range": joint_reset_range,
                    "asset_cfg": asset_cfg,
                },
            )
        },
    )

def get_ur10_robot_config_type_task(
    name: str,
    pos: tuple[float, float, float],
    rot: tuple[float, float, float, float],
) -> RobotConfig:
    from multi_robot_rl.configs import type_constants
    return _get_ur10_robot_config(
        name,
        entity_cfg=get_ur10e_entity_cfg_for_type_task(pos=pos, rot=rot),
        joint_reset_range=type_constants.UR10_JOINT_RESET_RANGE,
    )


def get_ur10_robot_config_reach_task(
    name: str,
    pos: tuple[float, float, float],
    rot: tuple[float, float, float, float],
) -> RobotConfig:
    from multi_robot_rl.configs import reach_constants
    return _get_ur10_robot_config(
        name,
        entity_cfg=get_ur10e_entity_cfg_for_reach_task(pos=pos, rot=rot),
        joint_reset_range=reach_constants.UR10_JOINT_RESET_RANGE,
    )


def get_ur10_robot_config_push_task(
    name: str,
    pos: tuple[float, float, float],
    rot: tuple[float, float, float, float],
) -> RobotConfig:
    from multi_robot_rl.configs import push_constants
    return _get_ur10_robot_config(
        name,
        entity_cfg=get_ur10e_entity_cfg_for_push_task(pos=pos, rot=rot),
        joint_reset_range=push_constants.UR10_JOINT_RESET_RANGE,
    )

# =========================================================
# Reset function
# =========================================================

def _reset_ur10_joints(
    env: ManagerBasedRlEnv,
    env_ids: torch.Tensor | None,
    joint_reset_range: tuple[float, float],
    asset_cfg: SceneEntityCfg,
) -> None:
    """Reset UR10e joints to the home pose with small uniform noise on each joint."""
    if env_ids is None:
        env_ids = torch.arange(env.num_envs, device=env.device, dtype=torch.int)

    asset = env.scene[asset_cfg.name]
    default_joint_pos = asset.data.default_joint_pos
    default_joint_vel = asset.data.default_joint_vel

    n_joints = len(asset_cfg.joint_ids) if isinstance(asset_cfg.joint_ids, (list, tuple)) else default_joint_pos.shape[-1]

    joint_pos = default_joint_pos[env_ids][:, asset_cfg.joint_ids].clone()
    joint_pos += sample_uniform(*joint_reset_range, (len(env_ids), n_joints), env.device)

    joint_vel = default_joint_vel[env_ids][:, asset_cfg.joint_ids].clone()

    joint_ids = asset_cfg.joint_ids
    if isinstance(joint_ids, list):
        joint_ids = torch.tensor(joint_ids, device=env.device)

    asset.write_joint_state_to_sim(
        joint_pos,
        joint_vel,
        env_ids=env_ids,
        joint_ids=joint_ids,
    )
