"""Generate the code reference pages and navigation."""

import ast
from pathlib import Path
import mkdocs_gen_files

nav = mkdocs_gen_files.Nav()
package_descriptions: dict[str, str] = {}


def first_docstring_line(file_path: Path) -> str:
    """Return the first non-empty line of a module docstring, if available."""
    try:
        module = ast.parse(file_path.read_text(encoding="utf-8"))
        doc = ast.get_docstring(module)
    except (OSError, SyntaxError, UnicodeDecodeError):
        return ""

    if not doc:
        return ""

    for line in doc.splitlines():
        line = line.strip()
        if line:
            return line
    return ""

# Need to write to docs/reference for mkdocs-literate-nav. Let's make sure the root path respects mapping
for path in sorted(Path("src").rglob("*.py")):
    if path.parent.name == "__pycache__":
        continue

    # Path relative to src
    module_path = path.relative_to("src").with_suffix("")
    
    # Path for the markdown documentation
    doc_path = path.relative_to("src").with_suffix(".md")
    full_doc_path = Path("reference", doc_path)

    # Ensure mapping handles __init__ logic accurately
    parts = tuple(module_path.parts)

    if parts[-1] == "__init__":
        parts = parts[:-1]
        doc_path = doc_path.with_name("index.md")
        full_doc_path = full_doc_path.with_name("index.md")

        # Keep a stable package summary for the top-level reference landing page.
        if len(parts) == 1:
            pkg_name = parts[0]
            package_descriptions[pkg_name] = first_docstring_line(path)
    elif parts[-1] == "__main__":
        continue

    # Skip root level python files directly in src/ that have no parts
    if len(parts) == 0:
        continue

    # Links in reference/SUMMARY.md are relative to docs/reference/.
    nav[parts] = doc_path.as_posix()

    with mkdocs_gen_files.open(full_doc_path, "w") as fd:
        ident = ".".join(parts)
        fd.write(f"---\ntitle: {ident}\n---\n\n# {ident}\n\n::: {ident}\n")

    mkdocs_gen_files.set_edit_path(full_doc_path, path)

with mkdocs_gen_files.open("reference/SUMMARY.md", "w") as nav_file:
    nav_file.write("* [Overview](index.md)\n")
    nav_file.writelines(nav.build_literate_nav())

with mkdocs_gen_files.open("reference/index.md", "w") as ref_index:
    ref_index.write("# API Reference\n\n")
    ref_index.write("This section contains autogenerated API documentation.\n\n")

    if package_descriptions:
        ref_index.write("## Packages\n\n")
        for package in sorted(package_descriptions):
            description = package_descriptions[package] or "Project package."
            ref_index.write(f"- [{package}]({package}/index.md): {description}\n")

    ref_index.write("\n## Navigation\n\n")
    ref_index.write("Use the sidebar to browse modules, functions, and classes.\n")
